# fly.toml app configuration file generated for jenzo on 2024-02-18T16:10:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jenzo'
primary_region = 'lhr'

[build]

[deploy]
  strategy = 'rolling'

[mounts]
  source = 'data'
  destination = '/app/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = 80
  CACHE_TTL = 10
  NODE_ENV = 'production'
